name: Publish NuGet Package

on: [push]

jobs:
  version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      assemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}
      informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.3.0
        with:
          versionSpec: '6.4.x'
          
      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.3.0

      - name: Display GitVersion outputs
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"

  build:
    needs: [version]
    runs-on: ubuntu-latest
    name: Build and Package
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0"

      - run: dotnet build src -c Release /p:AssemblyVersion=${{ needs.version.outputs.assemblySemFileVer }} /p:FileVersion=${{ needs.version.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ needs.version.outputs.sha }}
      - run: dotnet test src
      - run: dotnet pack src/Sessionize.Api.Client/Sessionize.Api.Client.csproj -c Release -p:AssemblyVersion=${{ needs.version.outputs.assemblySemFileVer }} -p:FileVersion=${{ needs.version.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ needs.version.outputs.sha }} -p:PackageVersion=${{ needs.version.outputs.majorMinorPatch }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v6
        with:
          name: nuget-package
          path: src/Sessionize.Api.Client/bin/Release/*${{ needs.version.outputs.majorMinorPatch }}.nupkg

  deploy:
    needs: [build, version]
    runs-on: ubuntu-latest
    name: Deploy NuGet Package
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # - run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
      - run: gh release create v${{ needs.version.outputs.majorMinorPatch }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: nuget-package
          path: ./package

      - name: Publish
        run: dotnet nuget push package/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
